import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import About from '../components/about/about';
import Footer from '../components/footer/footer';
import Header1 from '../components/Header1/Header';
import Achievement from '../components/Achievement/Achievement'
import Bg from '../pages/assets/bgWhite.png'
import Bunny from '../pages/assets/easter-bunny-google-3d-animal.gif'
import {Fade} from 'react-reveal';
import NavBar from '../components/NavBar/NavBar';
import Company from '../components/company/company'
import Testimonial from '../components/Testimonial/Testimonial';
import {Flex,Text} from '@chakra-ui/react'
import { useState } from 'react';

export default function Home() {
  useState(typeof window === "undefined");

const [isInFavorites, setIsInFavorites] = useState(typeof window === "undefined");
  return (
    <div className={styles.animation}>
    <div className={styles.container}>
      <Head>
        <title>Myself</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar styles={styles} />
      <Fade top>
      <Header1 styles={styles}/>
      </Fade>
      <Fade buttom>
      <Testimonial />
      </Fade>
      <Fade buttom>
      <Achievement styles={styles}/>
      </Fade>
      <Fade buttom>
      <About styles={styles} />
      </Fade>
      <Fade buttom>
        <Company styles={styles} />
      </Fade>
      <Flex
      flexDirection={'column'}
        justifyContent={'center'}
        alignItems={'center'}
        mt={20}>
          <Text
          fontFamily={'cursive'}
          fontSize={45}
          fontWeight={700}>GooDBye!!</Text>
      <Image src={Bunny} style={{opacity:0.2}} alt="" />
      </Flex>
      <Fade buttom>
        
      <Footer styles={styles} />
      </Fade>
  
    </div>
    </div>
  )
}
